ARG base
FROM ${base}

# Refer to DL4006 for details.
SHELL [ "/bin/bash", "-o", "pipefail" ]

# If you want to avoid warnings about DL3004 on sudo usage, either
# ignore it with ""
# USER root

USER gitpod
