repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "3.0.0"
    hooks:
      - id: forbid-binary
      - id: script-must-have-extension
      - id: shellcheck
      - id: shfmt

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [
          "--ignore",
          "CHANGELOG.md",
          "--disable",
          "MD013"
        ]

# TODO: enable after fixing lint errors
  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.4.1
  #   hooks:
  #     - id: hadolint-docker
